# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: maria-db
    image: mariadb:10.10.5-jammy
    restart: no
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    container_name: adminer
    image: adminer
    restart: no
    ports:
      - 8081:8080

#version: '3'

#services:
  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev:v3
    restart: no
    ports:
      - 9081:80
      - 9025:25
